### ISSUE TITLE
代码高亮自定义风格，怎么设置的

### ISSUE THREAD

**Issue by iuimm** [JaxsonWang/Prism.js-Style#1]
![tim 20180709055218](https://user-images.githubusercontent.com/35288212/42424301-c651d2b6-833c-11e8-9feb-7770151434cf.png)
![tim 20180709054737](https://user-images.githubusercontent.com/35288212/42424302-c977164a-833c-11e8-8f19-68cf2a6d920d.png)
搞了一会儿  不可以 希望指点

**Comment by JaxsonWang** [comment]
你可以把css文件下载，放入你的网站目录下，填入相对url地址即可。
